version: '3'

services:
  app:
    container_name: app
    build: .
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./app/:/app/
      - /app/node_modules/
    command: /bin/sh -c "python3 sim.py && npm start"
