version: '3'

services:

  backend:
    build: ./backend
    volumes: 
      - ./backend:/backend/
    ports:
      - 5000:5000
    ### Connect using localhost:5001

  app:
    build: ./app 
    volumes: 
      - ./app:/app/
    ports:
      - 3000:3000